/* TRACE BENCH bilingual copy and shared site initialization. */

const I18N = {
  en: {
    nav_evidence: 'Evidence',
    nav_framework: 'Framework',
    nav_results: 'Leaderboard',
    nav_data: 'Dataset',
    hero_badge: 'Kuaishou GameMind Lab',
    hero_subtitle: 'Task-driven Roleplay Agentic Checklist Evaluation',
    hero_desc:
      'Roleplay evaluation should reveal what was tested, what failed, and which dialogue evidence supports the judgment. TRACE BENCH turns each role profile into a fixed checklist, then adaptively verifies it through natural multi-turn interaction.',
    btn_paper: 'Read Paper',
    btn_framework: 'Explore Method',
    stat_cases: 'Evaluation Cases',
    stat_items: 'Checklist Items',
    stat_models: 'Evaluated Models',
    scroll_hint: 'Trace the evidence',
    evidence_tag: 'Validity at a Glance',
    evidence_title: 'Coverage is engineered, not assumed.',
    evidence_sub:
      'TRACE BENCH actively reaches fixed role requirements and preserves the evidence needed to audit every judgment.',
    coverage_free: 'MiniMax free dialogue',
    coverage_free_note: '102 messages, 292 items uncovered',
    coverage_trace_note: 'At most 65 messages, 1 item uncovered',
    coverage_note:
      'Coverage = (completed + failed) / total. It measures whether an item was tested, not whether the model passed it.',
    audit_label: 'Human audit',
    audit_desc: 'Agreement with human majority over 600 checklist items.',
    hygiene_label: 'Protocol hygiene',
    hygiene_desc: 'Seeded case-runs contaminated by a fixed first message.',
    hygiene_detail: 'Removed in the final protocol',
    evolution_label: 'Closed-loop evolution',
    evolution_desc: 'Mean CC change under refined verification flows.',
    evolution_detail: 'Same requirements and denominator',
    framework_tag: 'Traceable Evaluation',
    framework_title: 'Fixed targets. Adaptive dialogue. Auditable scores.',
    framework_sub:
      'Scored requirements are built once from the role profile. The User Agent changes only how those requirements are elicited and verified.',
    method_offline: 'Offline construction',
    method_checklist: 'Fixed role-specific checklist',
    method_profile: 'Role + scenario specification',
    check_identity: 'Stay in role',
    check_relation: 'Remember relationship',
    check_world: 'Maintain world knowledge',
    check_goal: 'Follow interaction goal',
    check_memory: 'Recall injected fact',
    method_fixed: 'Built once and fixed across models',
    method_online: 'Online interaction',
    method_dialogue: 'Roleplay dialogue + private tracker',
    dialogue_user: 'User Agent',
    dialogue_u1: 'Rowan, the North Gate sent me. I carry the watch token.',
    dialogue_target: 'Roleplay Model',
    dialogue_t1: 'Then the watch trusts you. The archive seals changed after dusk.',
    dialogue_evidence: 'Evidence: watch token recognized',
    private_label: 'private',
    status_completed: 'completed',
    status_progress: 'in progress',
    status_failed: 'failed',
    method_private: 'Planning and tool results never enter public dialogue',
    method_output: 'Evidence output',
    method_trace: 'Checklist state trace',
    method_audit: 'Every terminal judgment keeps supporting dialogue evidence',
    method_next: 'Next evaluation',
    method_evolution: 'Closed-loop benchmark evolution',
    loop_base: 'Base traces',
    loop_failed: 'Failed items',
    loop_flows: 'Refined flows',
    loop_desc:
      'Effective verification actions are distilled from failed traces. Role requirements and the scoring denominator stay fixed.',
    loop_fixed: 'Verification evolves; requirements do not',
    state_tag: 'State Machine',
    state_title: 'Termination is gated by evidence.',
    state_desc:
      'Every item must reach a terminal state with evidence before the conversation-finish tool can release the evaluation.',
    state_nonterminal: 'non-terminal',
    state_reversible: 'can flip to failed',
    state_sticky: 'sticky',
    state_untestable: 'untestable',
    state_release: 'Finish evaluation',
    state_release_rule: 'all items terminal + evidence attached',
    scoring_tag: 'Composite Reporting',
    scoring_title: 'Five dimensions, one explicit contract.',
    metric_cc: 'Completed non-STM role requirements over all non-STM prebuilt items.',
    metric_stm: 'Cases that complete the cross-turn user-injected fact probe.',
    metric_div: 'Character-bigram sentence similarity mapped to a repetition penalty.',
    metric_lq: 'Per-reply LLM judgment of fluency, usage, and internal logic.',
    metric_len: 'Deterministic language-aware bounds for response length.',
    results_tag: '26-model Leaderboard',
    results_title: 'Overall ranking with capability breakdowns.',
    results_sub:
      'Results use the same 200 cases and 5,498 fixed checklist items. Overall follows the five-dimension weighted formula; C-to-F is diagnostic only.',
    results_note:
      'The paper reports 100% Covered Rate for the main benchmark and therefore omits it from the leaderboard.',
    results_paper: 'Open full tables and analysis',
    robust_tag: 'Protocol Reliability',
    robust_title: 'Stable rankings under controlled variation.',
    repeat_title: 'Repeated runs',
    repeat_desc: 'All six tested models preserve their ordering across three independent runs.',
    replace_title: 'User Agent replacement',
    replace_value: '0 rank changes',
    replace_desc: 'Three qualified User Agents produce exactly the same six-model ordering.',
    strict_title: 'Strict failure',
    strict_desc: 'Later counterevidence can overturn success; failure evidence cannot be erased.',
    data_tag: 'Benchmark Instance',
    data_title: 'Two sources, one shared scoring denominator.',
    data_sub:
      'Every case packages a target role profile, user profile, interaction scene, and fixed checklist for repeated evaluation across models.',
    data_ce_title: 'CharacterEval-derived cases',
    data_ce_desc:
      'Original public character profiles supplemented with scenes and user-side context.',
    data_scenario_title: 'Scenario-generated cases',
    data_scenario_desc:
      'Chinese-English roles with richer relationships, tasks, and behavioral constraints.',
    data_cases: 'evaluation cases',
    dimensions_title: 'Role-derived checklist coverage',
    dim_identity: 'Identity',
    dim_personality: 'Personality',
    dim_behavior: 'Behavior',
    dim_boundary: 'Ability boundaries',
    dim_style: 'Speaking style',
    dim_privacy: 'Privacy',
    dim_scene: 'Scene adaptation',
    dim_memory: 'Cross-turn memory',
    data_total_items: 'prebuilt checklist items in total',
    team_tag: 'Contributions',
    team_title: 'Kuaishou GameMind Lab',
    team_leader: 'Team Leader',
    project_leader: 'Project Leader',
    technical: 'Technical Implementation',
    human_eval: 'Human Evaluation',
    affiliation: 'Affiliation',
    team_equal: '<sup>*</sup> Equal contribution to technical implementation.',
    cite_title: 'Citation',
    cite_note: 'Institutional citation follows the current paper title page.',
    footer_links_title: 'Research Links',
    footer_paper: 'Paper PDF',
    footer_framework: 'Framework',
    footer_trace: 'Test what matters. Trace every judgment.',
  },
  zh: {
    nav_evidence: '实验依据',
    nav_framework: '评测框架',
    nav_results: '排行榜',
    nav_data: '数据集',
    hero_badge: '快手 GameMind 实验室',
    hero_subtitle: '任务驱动的角色扮演 Agent 清单评测',
    hero_desc:
      '角色扮演评测不应只给出单一分数，还应揭示测试了什么、哪里失败，以及哪些对话证据支持判断。TRACE BENCH 将角色设定转为固定清单，再通过自然多轮交互自适应地完成验证。',
    btn_paper: '阅读论文',
    btn_framework: '查看方法',
    stat_cases: '评测用例',
    stat_items: '清单条目',
    stat_models: '参评模型',
    scroll_hint: '沿证据向下',
    evidence_tag: '有效性概览',
    evidence_title: '覆盖不是假设出来的，而是主动验证出来的。',
    evidence_sub: 'TRACE BENCH 主动触达固定的角色要求，并保留审计每项判断所需的证据。',
    coverage_free: 'MiniMax 自由对话',
    coverage_free_note: '102 条消息，292 项未覆盖',
    coverage_trace_note: '最多 65 条消息，仅 1 项未覆盖',
    coverage_note:
      '覆盖率 =（completed + failed）/ total。它衡量条目是否被测试，不等同于模型是否通过。',
    audit_label: '人工审计',
    audit_desc: '在 600 个清单条目上与人工多数标签的一致率。',
    hygiene_label: '协议清洁度',
    hygiene_desc: '固定首条消息导致证据污染的用例运行占比。',
    hygiene_detail: '最终协议已移除固定开场',
    evolution_label: '闭环演进',
    evolution_desc: '使用精炼验证流程后的平均 CC 变化。',
    evolution_detail: '要求与评分分母保持不变',
    framework_tag: '可追溯评测',
    framework_title: '目标固定，对话自适应，分数可审计。',
    framework_sub: '评分要求从角色设定一次性构建。User Agent 只改变如何触发和验证这些要求。',
    method_offline: '离线构建',
    method_checklist: '固定的角色专属清单',
    method_profile: '角色 + 场景规范',
    check_identity: '保持角色身份',
    check_relation: '记住人物关系',
    check_world: '维持世界知识',
    check_goal: '遵循交互目标',
    check_memory: '回忆注入事实',
    method_fixed: '一次构建，跨模型固定',
    method_online: '在线交互',
    method_dialogue: '角色对话 + 私有追踪器',
    dialogue_user: 'User Agent',
    dialogue_u1: 'Rowan 让我从北门来，我带着守望者的信物。',
    dialogue_target: 'Roleplay Model',
    dialogue_t1: '那守望者信任你。黄昏后，档案馆的封印发生了变化。',
    dialogue_evidence: '证据：识别出守望者信物',
    private_label: '私有',
    status_completed: '已完成',
    status_progress: '进行中',
    status_failed: '失败',
    method_private: '规划和工具结果不会进入公开对话',
    method_output: '证据输出',
    method_trace: '清单状态轨迹',
    method_audit: '每个终态判断都保留相应对话证据',
    method_next: '下一轮评测',
    method_evolution: '闭环基准演进',
    loop_base: '基础轨迹',
    loop_failed: '失败条目',
    loop_flows: '精炼流程',
    loop_desc: '从失败轨迹中提炼有效验证动作；角色要求和评分分母始终保持固定。',
    loop_fixed: '演进的是验证方式，不是评测要求',
    state_tag: '状态机',
    state_title: '结束评测必须通过证据门禁。',
    state_desc: '每个条目必须进入带有证据的终态，conversation-finish 工具才允许结束评测。',
    state_nonterminal: '非终态',
    state_reversible: '可翻转为 failed',
    state_sticky: '不可恢复',
    state_untestable: '当前场景不可测',
    state_release: '结束评测',
    state_release_rule: '全部条目终态 + 证据完整',
    scoring_tag: '综合报告',
    scoring_title: '五个维度，一份明确的评分契约。',
    metric_cc: '全部非 STM 预建条目中，最终 completed 的角色要求占比。',
    metric_stm: '跨轮用户注入事实探针达到 completed 的用例占比。',
    metric_div: '使用字符二元组句子相似度计算归一化重复惩罚。',
    metric_lq: '逐回复判断流畅度、用法与内部逻辑的 LLM 评分。',
    metric_len: '根据语言类型使用确定性的回复长度区间。',
    results_tag: '26 模型排行榜',
    results_title: '总排名与能力维度拆解。',
    results_sub:
      '所有模型使用相同的 200 个用例和 5,498 个固定清单条目。Overall 按五维公式计算，C→F 仅作诊断。',
    results_note: '论文报告主榜所有模型 Covered Rate 均为 100%，因此榜单不再单列该指标。',
    results_paper: '打开论文完整表格与分析',
    robust_tag: '协议可靠性',
    robust_title: '受控变化下，模型排序保持稳定。',
    repeat_title: '重复运行',
    repeat_desc: '六个受测模型在三次独立运行中保持相同排序。',
    replace_title: '替换 User Agent',
    replace_value: '排名变化 0 次',
    replace_desc: '三个合格 User Agent 得到完全相同的六模型排序。',
    strict_title: '严格失败',
    strict_desc: '后续反证可以推翻成功；已经形成的失败证据不会被抹去。',
    data_tag: '基准实例',
    data_title: '两类数据来源，共用同一评分分母。',
    data_sub: '每个用例都包含目标角色设定、用户设定、交互场景和固定清单，可跨模型重复评测。',
    data_ce_title: 'CharacterEval 衍生用例',
    data_ce_desc: '保留公开角色设定，并补充交互场景与用户侧上下文。',
    data_scenario_title: '场景生成用例',
    data_scenario_desc: '中英文角色，包含更丰富的人物关系、任务和行为约束。',
    data_cases: '个评测用例',
    dimensions_title: '角色清单覆盖维度',
    dim_identity: '身份',
    dim_personality: '性格',
    dim_behavior: '行为模式',
    dim_boundary: '能力边界',
    dim_style: '说话风格',
    dim_privacy: '隐私约束',
    dim_scene: '场景适应',
    dim_memory: '跨轮记忆',
    data_total_items: '个预建清单条目',
    team_tag: '项目贡献',
    team_title: '快手 GameMind 实验室',
    team_leader: '团队负责人',
    project_leader: '项目负责人',
    technical: '技术实现',
    human_eval: '人工评测',
    affiliation: '所属机构',
    team_equal: '<sup>*</sup> 技术实现同等贡献。',
    cite_title: '引用',
    cite_note: '当前机构引用与论文标题页保持一致。',
    footer_links_title: '研究链接',
    footer_paper: '论文 PDF',
    footer_framework: '评测框架',
    footer_trace: '测试关键要求，追溯每项判断。',
  },
};

initSite({
  storageKey: 'trace-bench-lang',
  i18n: I18N,
  counterDuration: 1200,
  onRefresh: () => {
    if (typeof refreshFigures === 'function') refreshFigures();
  },
});
